<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<test-results name="G:\Arquivos\Teste Unitario Delphi-Horse\testback\Win32\Debug\Testsback.exe" total="2" errors="2" failures="0" ignored="0" inconclusive="0" not-run="0" skipped="0" invalid="0" date="2024-05-23" time="0.001">
  <culture-info current-culture="en" current-uiculture="en" />
  <test-suite type="Assembly" name="Testsback.exe" executed="true" result="Failure" success="False" time="0.001" asserts="0">
    <results>
        <test-suite type="Namespace" name="TestPerson" executed="true" result="Success" success="True" time="0.001" asserts="0" >
          <results>
              <test-suite type="Fixture" name="TestTPersonTest" executed="True" result="Success" success="True" time="0.001" >
                <results>
                  <test-case name="TestIDtreatment" executed="True" result="Error" success="False" time="0.000" asserts="0" >
                    <failure>
                      <message>
                        <![CDATA[ Access violation at address 00A45566 in module 'Testsback.exe'. Read of address 00000068 ]]>
                      </message>
                      <stack-trace>
                        <![CDATA[  ]]>
                      </stack-trace>
                    </failure>
                  </test-case>
                  <test-case name="TestCPFCNPJtreatment" executed="True" result="Error" success="False" time="0.000" asserts="0" >
                    <failure>
                      <message>
                        <![CDATA[ Access violation at address 00A45566 in module 'Testsback.exe'. Read of address 00000068 ]]>
                      </message>
                      <stack-trace>
                        <![CDATA[  ]]>
                      </stack-trace>
                    </failure>
                  </test-case>
                </results>
              </test-suite>
          </results>
        </test-suite>
    </results>
  </test-suite>
</test-results>
